name: SDK V2 Build

on:
  pull_request:
    paths:
      # - 'sdk_v2/**'
      - '.github/workflows/sdk_v2/**'
  push:
    paths:
      # - 'sdk_v2/**'
      - '.github/workflows/sdk_v2/**'
    branches:
      - main
  workflow_dispatch: # allows manual triggering from GitHub UI

jobs:
  build-cs:
    uses: ./.github/workflows/sdk_v2/templates/build-cs-steps.yml