name: SDK V2 Build

on:
  pull_request:
    paths:
      - 'sdk_v2/**'
      - '.github/workflows/**'
  push:
    paths:
      - 'sdk_v2/**'
      - '.github/workflows/**'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-cs-windows:
    uses: ./.github/workflows/build-cs-steps.yml
    with:
      version: '0.9.0.${{ github.run_number }}'
      platform: 'windows'
    secrets: inherit
  build-js-windows:
    uses: ./.github/workflows/build-js-steps.yml
    with:
      version: '0.9.0.${{ github.run_number }}'
      platform: 'windows'
    secrets: inherit

  build-cs-macos:
    uses: ./.github/workflows/build-cs-steps.yml
    with:
      version: '0.9.0.${{ github.run_number }}'
      platform: 'macos'
    secrets: inherit
  build-js-macos:
    uses: ./.github/workflows/build-js-steps.yml
    with:
      version: '0.9.0.${{ github.run_number }}'
      platform: 'macos'
    secrets: inherit

  build-cs-linux:
    uses: ./.github/workflows/build-cs-steps.yml
    with:
      version: '0.9.0.${{ github.run_number }}'
      platform: 'ubuntu'
    secrets: inherit
  build-js-linux:
    uses: ./.github/workflows/build-js-steps.yml
    with:
      version: '0.9.0.${{ github.run_number }}'
      platform: 'ubuntu'
    secrets: inherit
